/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

/**
 * Exact birth details required for an accurate sidereal chart.
 */
export interface KundaliInput {
  /** @minLength 1 */
  name: string;
  /**
     * Birth date, YYYY-MM-DD (Gregorian calendar).
     * @pattern ^\d{4}-\d{2}-\d{2}$
     */
  date: string;
  /**
     * Local birth time, 24h HH:MM, as it appeared on a clock at the birth place.
     * @pattern ^\d{2}:\d{2}$
     */
  time: string;
  /**
     * @minimum -90
     * @maximum 90
     */
  latitude: number;
  /**
     * @minimum -180
     * @maximum 180
     */
  longitude: number;
  place: string;
}

export interface KundaliError {
  error: string;
}

export interface Planet {
  name: string;
  sanskrit: string;
  symbol: string;
  /** Sidereal ecliptic longitude, 0-360° */
  longitude: number;
  /** Degrees elapsed within its rashi, 0-30 */
  degreeInSign: number;
  /**
     * @minimum 1
     * @maximum 12
     */
  rashi: number;
  rashiName: string;
  rashiSymbol: string;
  nakshatra: string;
  /**
     * @minimum 1
     * @maximum 4
     */
  nakshatraPada: number;
  nakshatraLord: string;
  /**
     * @minimum 1
     * @maximum 12
     */
  house: number;
  isRetrograde: boolean;
  isCombust: boolean;
  /**
     * Exalted, Debilitated, Own Sign, Moolatrikona or null
     * @nullable
     */
  dignity?: string | null;
  color: string;
}

export interface CrystalRec {
  crystal: string;
  reason: string;
  planet: string;
  image: string;
  benefit: string;
}

export interface Yoga {
  name: string;
  description: string;
  strength: string;
}

export interface Dosha {
  name: string;
  description: string;
  remedy: string;
  /** Low, Moderate or High */
  severity: string;
}

export interface AntarDasha {
  lord: string;
  startDate: string;
  endDate: string;
}

export interface DashaPeriod {
  lord: string;
  startDate: string;
  endDate: string;
  years: number;
  antardashas?: AntarDasha[];
}

export interface Panchang {
  tithi: string;
  tithiNumber: number;
  /** Shukla (waxing) or Krishna (waning) */
  paksha: string;
  nakshatra: string;
  nakshatraPada: number;
  /** Nitya yoga (Vishkambha, Priti, ...) */
  yogaName: string;
  karana: string;
  /** Weekday */
  vara: string;
  sunrise: string;
  sunset: string;
}

export interface KundaliChart {
  /**
     * @minimum 1
     * @maximum 12
     */
  lagna: number;
  lagnaName: string;
  lagnaSymbol: string;
  lagnaLongitude: number;
  planets: Planet[];
  houseRashis: number[];
  moonSign: string;
  moonSignSymbol: string;
  sunSign: string;
  nakshatra: string;
  nakshatraPada: number;
  nakshatraLord: string;
  crystalRecommendations: CrystalRec[];
  yogas: Yoga[];
  doshas: Dosha[];
  currentDasha: DashaPeriod;
  currentAntardasha?: AntarDasha;
  dashaSequence: DashaPeriod[];
  panchang: Panchang;
  ayanamsa: number;
}

