import os
import re
import json
import time
from concurrent.futures import ThreadPoolExecutor
from PIL import Image
import pillow_heif

pillow_heif.register_heif_opener()

BASE_DIR = "Website Crystal Bracelet Catalogue"
OUT_BASE = os.path.join("public", "products")
os.makedirs(OUT_BASE, exist_ok=True)

# Define metadata for each of the 81 folders
PRODUCT_CONFIGS = {
    "Amazonite": {
        "slug": "amazonite-classic",
        "name": "Amazonite Classic Harmony Bracelet",
        "beadSize": "8mm",
        "material": "Natural Amazonite, Durable Stretch Cord",
        "gemstone": "Amazonite",
        "price": 1099,
        "originalPrice": 1499,
        "badge": "BEST SELLER",
        "swatches": ["#7ec8b8", "#a8dadc"],
        "concern": ["peace", "health"],
        "zodiac": ["Virgo", "Aries"],
        "chakra": "Throat & Heart Chakra",
        "description": "Handcrafted with authentic soothing Amazonite beads known as the stone of courage and truth. Dissipates negative energy and calms the nervous system.",
    },
    "Amazonite 10MM": {
        "slug": "amazonite-10mm",
        "name": "Amazonite 10MM Power Energy Bracelet",
        "beadSize": "10mm",
        "material": "Grade-A Amazonite (10mm), High-Tensile Elastic",
        "gemstone": "Amazonite",
        "price": 1399,
        "originalPrice": 1799,
        "badge": "NEW",
        "swatches": ["#7ec8b8", "#457b9d"],
        "concern": ["peace", "health"],
        "zodiac": ["Virgo"],
        "chakra": "Throat Chakra",
        "description": "Bold 10mm Amazonite beads provide a strong energetic shield against electromagnetic stress while enhancing articulate self-expression.",
    },
    "Amazonite 8MM": {
        "slug": "amazonite-8mm",
        "name": "Amazonite 8MM Expression & Truth Bracelet",
        "beadSize": "8mm",
        "material": "Selected Natural Amazonite (8mm), Elastic Cord",
        "gemstone": "Amazonite",
        "price": 1199,
        "originalPrice": 1599,
        "badge": None,
        "swatches": ["#7ec8b8", "#a8dadc"],
        "concern": ["peace"],
        "zodiac": ["Virgo", "Aries"],
        "chakra": "Throat Chakra",
        "description": "Classic 8mm polished Amazonite beads encourage peaceful dialogue, inner balance, and deep emotional clarity.",
    },
    "Amethyst": {
        "slug": "amethyst-classic",
        "name": "Spiritual Amethyst Meditation Bracelet",
        "beadSize": "8mm",
        "material": "Natural Deep Purple Amethyst, Stretch Cord",
        "gemstone": "Amethyst",
        "price": 1199,
        "originalPrice": 1599,
        "badge": "BEST SELLER",
        "swatches": ["#7b2cbf", "#9d4edd"],
        "concern": ["peace", "protection"],
        "zodiac": ["Aquarius", "Pisces"],
        "chakra": "Crown & Third Eye Chakra",
        "description": "Consecrated with Vedic mantras under the full moon to awaken spiritual wisdom, relieve insomnia, and calm restless thoughts.",
    },
    "Amethyst 10MM": {
        "slug": "amethyst-10mm",
        "name": "Royal Amethyst 10MM Aura Cleansing Bracelet",
        "beadSize": "10mm",
        "material": "Deep Purple Brazilian Amethyst (10mm), Elastic",
        "gemstone": "Amethyst",
        "price": 1499,
        "originalPrice": 1999,
        "badge": "NEW",
        "swatches": ["#5a189a", "#7b2cbf"],
        "concern": ["peace", "protection"],
        "zodiac": ["Aquarius", "Pisces"],
        "chakra": "Crown Chakra",
        "description": "Substantial 10mm Amethyst spheres emit high-frequency spiritual vibrations, providing an energetic cocoon against negative vibes.",
    },
    "Amethyst 8MM": {
        "slug": "amethyst-8mm",
        "name": "Pure Amethyst 8MM Stress Relief Bracelet",
        "beadSize": "8mm",
        "material": "Natural Amethyst Beads (8mm), Stretch String",
        "gemstone": "Amethyst",
        "price": 1099,
        "originalPrice": 1499,
        "badge": "SALE",
        "swatches": ["#7b2cbf", "#c77dff"],
        "concern": ["peace"],
        "zodiac": ["Aquarius", "Pisces"],
        "chakra": "Crown Chakra",
        "description": "Ideal everyday spiritual companion for daily mindfulness, anxiety relief, and deep restorative sleep.",
    },
    "Anti Anger-Self Love": {
        "slug": "anti-anger-self-love",
        "name": "Anti-Anger & Self-Love Healing Bracelet",
        "beadSize": "8mm",
        "material": "Rose Quartz, Howlite & Rhodonite Synergy Blend",
        "gemstone": "Multi-stone",
        "price": 1399,
        "originalPrice": 1899,
        "badge": "BEST SELLER",
        "swatches": ["#f48fb1", "#f5f5f5", "#c2185b"],
        "concern": ["love", "peace"],
        "zodiac": ["Taurus", "Cancer", "Libra"],
        "chakra": "Heart Chakra",
        "description": "Formulated specifically to dissolve bottled-up frustration, emotional volatility, and resentment, replacing them with tender self-acceptance.",
    },
    "Azurite 8MM": {
        "slug": "azurite-8mm",
        "name": "Rare Azurite 8MM Third Eye Awakening Bracelet",
        "beadSize": "8mm",
        "material": "Natural Deep Blue Azurite Beads (8mm), Elastic",
        "gemstone": "Azurite",
        "price": 1799,
        "originalPrice": 2399,
        "badge": "NEW",
        "swatches": ["#1d3557", "#457b9d"],
        "concern": ["peace", "protection"],
        "zodiac": ["Sagittarius", "Aquarius"],
        "chakra": "Third Eye Chakra",
        "description": "Often called the Stone of Heaven, rare Azurite clears psychic blockages, unlocks intuitive sight, and enhances meditation depth.",
    },
    "Black Tourmaline": {
        "slug": "black-tourmaline-classic",
        "name": "Black Tourmaline Root Defense Bracelet",
        "beadSize": "8mm",
        "material": "Raw Black Tourmaline Polished Spheres, Elastic",
        "gemstone": "Black Tourmaline",
        "price": 1099,
        "originalPrice": 1499,
        "badge": "BEST SELLER",
        "swatches": ["#1a1a1a", "#333333"],
        "concern": ["protection"],
        "zodiac": ["Capricorn", "Scorpio"],
        "chakra": "Root Chakra",
        "description": "The ultimate psychic shield. Grounds spiritual energy while neutralizing environmental toxins, negative thoughts, and psychic vampirism.",
    },
    "Black Tourmaline 10MM": {
        "slug": "black-tourmaline-10mm",
        "name": "Black Tourmaline 10MM Aura Shield Bracelet",
        "beadSize": "10mm",
        "material": "Dense Black Tourmaline (10mm), Heavy Duty Elastic",
        "gemstone": "Black Tourmaline",
        "price": 1399,
        "originalPrice": 1899,
        "badge": "SALE",
        "swatches": ["#111111", "#222222"],
        "concern": ["protection"],
        "zodiac": ["Capricorn", "Scorpio"],
        "chakra": "Root Chakra",
        "description": "Heavyweight 10mm protection spheres establish an impenetrable energetic fortress around the bearer's aura.",
    },
    "Black Tourmaline 8MM": {
        "slug": "black-tourmaline-8mm",
        "name": "Black Tourmaline 8MM Psychic Protection Bracelet",
        "beadSize": "8mm",
        "material": "Genuine Black Tourmaline (8mm), Elastic Cord",
        "gemstone": "Black Tourmaline",
        "price": 1199,
        "originalPrice": 1599,
        "badge": None,
        "swatches": ["#1a1a1a"],
        "concern": ["protection"],
        "zodiac": ["Capricorn", "Scorpio"],
        "chakra": "Root Chakra",
        "description": "Essential daily armor for empaths, healers, and professionals working in high-stress or emotionally dense environments.",
    },
    "CQ": {
        "slug": "clear-quartz-classic",
        "name": "Clear Quartz (Sphatik) Master Healer Bracelet",
        "beadSize": "8mm",
        "material": "Natural Clear Quartz Crystal (Sphatik), Elastic",
        "gemstone": "Clear Quartz",
        "price": 999,
        "originalPrice": 1399,
        "badge": "BEST SELLER",
        "swatches": ["#ffffff", "#e0e0e0"],
        "concern": ["peace", "health"],
        "zodiac": ["All Signs"],
        "chakra": "All Chakras (Crown Primary)",
        "description": "Pure Himalayan Sphatik beads amplify spiritual intentions, clarify mental fog, and balance the bio-electromagnetic field.",
    },
    "CQ 10MM": {
        "slug": "clear-quartz-10mm",
        "name": "Clear Quartz 10MM Master Amplification Bracelet",
        "beadSize": "10mm",
        "material": "Optical Grade Clear Quartz (10mm), Elastic",
        "gemstone": "Clear Quartz",
        "price": 1299,
        "originalPrice": 1699,
        "badge": "NEW",
        "swatches": ["#ffffff", "#f5f5f5"],
        "concern": ["peace", "health"],
        "zodiac": ["All Signs"],
        "chakra": "Crown Chakra",
        "description": "10mm crystalline globes radiate supreme light frequency, purifying any stagnant energy in your personal sanctuary.",
    },
    "CQ 12MM": {
        "slug": "clear-quartz-12mm",
        "name": "Clear Quartz 12MM Sovereign Statement Bracelet",
        "beadSize": "12mm",
        "material": "Rare Jumbo Clear Quartz (12mm), Heavy Cord",
        "gemstone": "Clear Quartz",
        "price": 1599,
        "originalPrice": 2199,
        "badge": "NEW",
        "swatches": ["#ffffff"],
        "concern": ["peace", "health"],
        "zodiac": ["All Signs"],
        "chakra": "Crown Chakra",
        "description": "Majestic 12mm water-clear Sphatik beads. Designed for master practitioners, energy workers, and crystal connoisseurs.",
    },
    "CQ 8MM": {
        "slug": "clear-quartz-8mm",
        "name": "Clear Quartz 8MM Divine Radiance Bracelet",
        "beadSize": "8mm",
        "material": "Pure Sphatik Quartz Beads (8mm), Elastic",
        "gemstone": "Clear Quartz",
        "price": 1099,
        "originalPrice": 1499,
        "badge": None,
        "swatches": ["#ffffff"],
        "concern": ["peace", "health"],
        "zodiac": ["All Signs"],
        "chakra": "Crown Chakra",
        "description": "Cooling and purifying on the wrist, harmonizing planetary imbalances and enhancing concentration.",
    },
    "CQ Cut 10MM": {
        "slug": "clear-quartz-cut-10mm",
        "name": "Faceted Clear Quartz Cut 10MM Diamond-Facet Bracelet",
        "beadSize": "10mm Cut",
        "material": "Diamond-Cut Faceted Sphatik Quartz (10mm), Elastic",
        "gemstone": "Clear Quartz",
        "price": 1499,
        "originalPrice": 1999,
        "badge": "BEST SELLER",
        "swatches": ["#ffffff", "#e0e0e0"],
        "concern": ["peace", "health", "money"],
        "zodiac": ["All Signs"],
        "chakra": "Crown Chakra",
        "description": "Precision micro-faceted 10mm Sphatik gems catch and refract sunlight into prismatic rainbows, raising physical vibration.",
    },
    "CQ Cut 8MM": {
        "slug": "clear-quartz-cut-8mm",
        "name": "Faceted Clear Quartz Cut 8MM Prismatic Light Bracelet",
        "beadSize": "8mm Cut",
        "material": "Diamond-Faceted Pure Quartz (8mm), Elastic",
        "gemstone": "Clear Quartz",
        "price": 1299,
        "originalPrice": 1699,
        "badge": "SALE",
        "swatches": ["#ffffff", "#f0f0f0"],
        "concern": ["peace", "health"],
        "zodiac": ["All Signs"],
        "chakra": "Crown Chakra",
        "description": "Sparkling multifaceted Sphatik beads create a continuous halo of clarity, shielding your personal prana throughout the day.",
    },
    "Carnelian": {
        "slug": "carnelian-classic",
        "name": "Sacred Carnelian Fire Bracelet",
        "beadSize": "8mm",
        "material": "Natural Sunset Carnelian Agate, Elastic Cord",
        "gemstone": "Carnelian",
        "price": 999,
        "originalPrice": 1399,
        "badge": "BEST SELLER",
        "swatches": ["#d94e24", "#e76f51"],
        "concern": ["health", "love"],
        "zodiac": ["Aries", "Leo", "Virgo"],
        "chakra": "Sacral & Root Chakra",
        "description": "Known as the Singer's Stone and ancient talisman of courage. Kindles the fire of passion, motivation, and physical stamina.",
    },
    "Carnelian 10MM": {
        "slug": "carnelian-10mm",
        "name": "Carnelian 10MM Vitality & Passion Bracelet",
        "beadSize": "10mm",
        "material": "Fiery Orange Carnelian (10mm), High-Grade Elastic",
        "gemstone": "Carnelian",
        "price": 1299,
        "originalPrice": 1699,
        "badge": "NEW",
        "swatches": ["#c1440e", "#e76f51"],
        "concern": ["health"],
        "zodiac": ["Aries", "Leo"],
        "chakra": "Sacral Chakra",
        "description": "Bold 10mm Carnelian beads stimulate circulation, dispel lethargy, and instill courageous determination.",
    },
    "Carnelian 8MM": {
        "slug": "carnelian-8mm",
        "name": "Carnelian 8MM Creative Fire Bracelet",
        "beadSize": "8mm",
        "material": "Polished Natural Carnelian (8mm), Elastic",
        "gemstone": "Carnelian",
        "price": 1099,
        "originalPrice": 1499,
        "badge": None,
        "swatches": ["#d94e24", "#f4a261"],
        "concern": ["health", "money"],
        "zodiac": ["Aries", "Virgo"],
        "chakra": "Sacral Chakra",
        "description": "Inspires artists, entrepreneurs, and leaders with unwavering focus and creative drive.",
    },
    "Cats Eye 8MM": {
        "slug": "cats-eye-8mm",
        "name": "Natural Cat's Eye (Lehsunia) 8MM Ketu Aura Shield Bracelet",
        "beadSize": "8mm",
        "material": "Natural Chatoyant Chrysoberyl Cat's Eye (8mm), Elastic",
        "gemstone": "Cats Eye",
        "price": 1599,
        "originalPrice": 2199,
        "badge": "BEST SELLER",
        "swatches": ["#a3b18a", "#588157"],
        "concern": ["protection", "money"],
        "zodiac": ["Pisces", "Scorpio"],
        "chakra": "Solar Plexus & Crown",
        "description": "Vedic gemstone for planet Ketu. Protects against sudden financial setbacks, evil eye, and hidden enemies while attracting sudden wealth.",
    },
    "Citrine Gem": {
        "slug": "citrine-gem-classic",
        "name": "Golden Citrine Gem-Cut Abundance Bracelet",
        "beadSize": "8mm Gem",
        "material": "Faceted Natural Citrine Quartz, Gold Elastic",
        "gemstone": "Citrine",
        "price": 1399,
        "originalPrice": 1899,
        "badge": "BEST SELLER",
        "swatches": ["#f39c12", "#f1c40f"],
        "concern": ["money", "health"],
        "zodiac": ["Gemini", "Leo", "Sagittarius"],
        "chakra": "Solar Plexus Chakra",
        "description": "The Merchant's Stone in exquisite gem cut. Directly channels the solar abundance ray to attract business prosperity and financial freedom.",
    },
    "Citrine Gem 10MM": {
        "slug": "citrine-gem-10mm",
        "name": "Golden Citrine Gem-Grade 10MM Wealth Attractor Bracelet",
        "beadSize": "10mm Gem",
        "material": "Gem-Grade Citrine Crystal (10mm), Elastic",
        "gemstone": "Citrine",
        "price": 1699,
        "originalPrice": 2299,
        "badge": "NEW",
        "swatches": ["#e67e22", "#f39c12"],
        "concern": ["money"],
        "zodiac": ["Leo", "Gemini"],
        "chakra": "Solar Plexus Chakra",
        "description": "Substantial 10mm gem-grade Citrine radiates optimism and unshakeable confidence, unlocking new streams of revenue.",
    },
    "Citrine Gem 8MM": {
        "slug": "citrine-gem-8mm",
        "name": "Golden Citrine Gem-Grade 8MM Prosperity Bracelet",
        "beadSize": "8mm Gem",
        "material": "Selected Transparent Golden Citrine (8mm), Elastic",
        "gemstone": "Citrine",
        "price": 1499,
        "originalPrice": 1999,
        "badge": "SALE",
        "swatches": ["#f1c40f", "#f39c12"],
        "concern": ["money"],
        "zodiac": ["Leo", "Sagittarius"],
        "chakra": "Solar Plexus Chakra",
        "description": "Does not hold negative energy, making it an everlasting magnet for joy, self-worth, and material wealth.",
    },
    "Dhanyog": {
        "slug": "dhanyog-wealth-synergy",
        "name": "Dhan Yog (Wealth & Abundance) Sacred Synergy Bracelet",
        "beadSize": "8mm",
        "material": "Pyrite, Citrine, Green Aventurine & Tiger Eye Synergy",
        "gemstone": "Multi-stone",
        "price": 1499,
        "originalPrice": 1999,
        "badge": "BEST SELLER",
        "swatches": ["#c8a951", "#ffd54f", "#81c784", "#8b6914"],
        "concern": ["money", "protection"],
        "zodiac": ["Taurus", "Leo", "Virgo", "Capricorn"],
        "chakra": "Solar Plexus & Heart",
        "description": "Formulated by Vedic Jyotish practitioners combining the 4 supreme wealth crystals: Pyrite for money luck, Citrine for cash flow, Green Aventurine for opportunity, and Tiger Eye for execution.",
    },
    "Education": {
        "slug": "education-focus-study",
        "name": "Saraswati Vidya & Focus Study Bracelet",
        "beadSize": "8mm",
        "material": "Sodalite, Rainbow Fluorite, Amethyst & Clear Quartz",
        "gemstone": "Multi-stone",
        "price": 1299,
        "originalPrice": 1699,
        "badge": "SALE",
        "swatches": ["#3f51b5", "#00bcd4", "#9c27b0", "#ffffff"],
        "concern": ["peace", "health"],
        "zodiac": ["Gemini", "Virgo", "Aquarius"],
        "chakra": "Third Eye & Throat Chakra",
        "description": "Consecrated with Saraswati Mantras for students, exam aspirants, and researchers. Banishes brain fog, calms exam jitters, and supercharges information retention.",
    },
    "Garnet": {
        "slug": "garnet-classic",
        "name": "Deep Crimson Garnet Prana Bracelet",
        "beadSize": "8mm",
        "material": "Natural Almandine Garnet, Elastic Cord",
        "gemstone": "Garnet",
        "price": 1199,
        "originalPrice": 1599,
        "badge": "BEST SELLER",
        "swatches": ["#6b0f1a", "#8b0000"],
        "concern": ["health", "love"],
        "zodiac": ["Capricorn", "Aquarius", "Aries"],
        "chakra": "Root Chakra",
        "description": "Deep wine-red Garnet rekindles passion, restores healthy libido, purifies toxins from the bloodstream, and grounds scattered prana.",
    },
    "Garnet 10MM": {
        "slug": "garnet-10mm",
        "name": "Bohemian Garnet 10MM Kundalini Strength Bracelet",
        "beadSize": "10mm",
        "material": "Selected Crimson Garnet (10mm), Strong Elastic",
        "gemstone": "Garnet",
        "price": 1499,
        "originalPrice": 1999,
        "badge": "NEW",
        "swatches": ["#4a0e17", "#6b0f1a"],
        "concern": ["health"],
        "zodiac": ["Capricorn", "Aries"],
        "chakra": "Root Chakra",
        "description": "Heavier 10mm Garnet beads deliver an unwavering feeling of physical security, survival instinct, and endurance.",
    },
    "Garnet 8MM": {
        "slug": "garnet-8mm",
        "name": "Bohemian Garnet 8MM Vitality & Passion Bracelet",
        "beadSize": "8mm",
        "material": "Natural Garnet Spheres (8mm), Elastic",
        "gemstone": "Garnet",
        "price": 1299,
        "originalPrice": 1699,
        "badge": None,
        "swatches": ["#6b0f1a"],
        "concern": ["health", "love"],
        "zodiac": ["Capricorn", "Aquarius"],
        "chakra": "Root Chakra",
        "description": "Known as the Stone of Commitment. Inspires devotion in relationships and revitalizes depleted bio-energy.",
    },
    "Garnet Gem 8MM": {
        "slug": "garnet-gem-8mm",
        "name": "Premium Faceted Garnet Gem 8MM Luxury Energy Bracelet",
        "beadSize": "8mm Gem",
        "material": "Micro-Faceted Gem-Grade Garnet (8mm), Elastic",
        "gemstone": "Garnet",
        "price": 1599,
        "originalPrice": 2199,
        "badge": "BEST SELLER",
        "swatches": ["#800020", "#6b0f1a"],
        "concern": ["love", "health"],
        "zodiac": ["Capricorn", "Scorpio"],
        "chakra": "Root & Heart Chakra",
        "description": "Luxurious faceted cut refracts blood-red light with royal grace. Ideal for evening wear, romance, and spiritual grounding.",
    },
    "Green Aventurine": {
        "slug": "green-aventurine-classic",
        "name": "Lucky Green Aventurine Opportunity Bracelet",
        "beadSize": "8mm",
        "material": "Natural Jade-Green Aventurine, Elastic Cord",
        "gemstone": "Green Aventurine",
        "price": 999,
        "originalPrice": 1399,
        "badge": "BEST SELLER",
        "swatches": ["#2d6a4f", "#52b788"],
        "concern": ["money", "love"],
        "zodiac": ["Taurus", "Virgo"],
        "chakra": "Heart Chakra",
        "description": "The Premier Stone of Opportunity and luck. Attracts favorable synchronicities, lottery luck, and commercial triumphs.",
    },
    "Green Aventurine 10MM": {
        "slug": "green-aventurine-10mm",
        "name": "Green Aventurine 10MM Prosperity & Growth Bracelet",
        "beadSize": "10mm",
        "material": "Vibrant Green Aventurine (10mm), Elastic",
        "gemstone": "Green Aventurine",
        "price": 1299,
        "originalPrice": 1699,
        "badge": "NEW",
        "swatches": ["#1b4332", "#40916c"],
        "concern": ["money"],
        "zodiac": ["Taurus", "Virgo"],
        "chakra": "Heart Chakra",
        "description": "10mm Aventurine beads anchor an expansive mindset of abundance, shielding the heart against financial anxiety.",
    },
    "Green Aventurine 8MM": {
        "slug": "green-aventurine-8mm",
        "name": "Green Aventurine 8MM Good Fortune Bracelet",
        "beadSize": "8mm",
        "material": "Selected Green Aventurine (8mm), Elastic",
        "gemstone": "Green Aventurine",
        "price": 1099,
        "originalPrice": 1499,
        "badge": "SALE",
        "swatches": ["#2d6a4f"],
        "concern": ["money", "health"],
        "zodiac": ["Taurus", "Virgo"],
        "chakra": "Heart Chakra",
        "description": "Daily talisman for wealth seekers, investors, and anyone undertaking a bold new business venture.",
    },
    "Health": {
        "slug": "health-wellness-vitality",
        "name": "Maha Mrityunjaya Wellness & Vitality Healing Bracelet",
        "beadSize": "8mm",
        "material": "Bloodstone, Green Jade, Clear Quartz & Carnelian",
        "gemstone": "Multi-stone",
        "price": 1399,
        "originalPrice": 1899,
        "badge": "BEST SELLER",
        "swatches": ["#2e7d32", "#81c784", "#f5f5f5", "#d94e24"],
        "concern": ["health"],
        "zodiac": ["All Signs"],
        "chakra": "Heart, Root & Solar Plexus",
        "description": "Vedic healing blend designed to strengthen cellular vitality, accelerate recovery from fatigue, and detoxify the physical vessel.",
    },
    "Heated Citrine": {
        "slug": "heated-citrine-classic",
        "name": "Radiant Golden Sun Citrine Bracelet",
        "beadSize": "8mm",
        "material": "Golden Madeira Citrine, Elastic Cord",
        "gemstone": "Citrine",
        "price": 1099,
        "originalPrice": 1499,
        "badge": "BEST SELLER",
        "swatches": ["#e67e22", "#d35400"],
        "concern": ["money"],
        "zodiac": ["Leo", "Gemini"],
        "chakra": "Solar Plexus Chakra",
        "description": "Warm golden-amber hues radiate cheerful enthusiasm and manifest new professional opportunities with ease.",
    },
    "Heated Citrine 10MM": {
        "slug": "heated-citrine-10mm",
        "name": "Golden Sun Citrine 10MM Solar Energy Bracelet",
        "beadSize": "10mm",
        "material": "Warm Honey Citrine (10mm), Strong Cord",
        "gemstone": "Citrine",
        "price": 1399,
        "originalPrice": 1799,
        "badge": "NEW",
        "swatches": ["#d35400", "#e67e22"],
        "concern": ["money"],
        "zodiac": ["Leo"],
        "chakra": "Solar Plexus Chakra",
        "description": "Bold 10mm golden beads provide a continuous solar recharge, eradicating lethargy and self-doubt.",
    },
    "Heated Citrine 8MM": {
        "slug": "heated-citrine-8mm",
        "name": "Golden Sun Citrine 8MM Radiance & Success Bracelet",
        "beadSize": "8mm",
        "material": "Sun-Kissed Amber Citrine (8mm), Elastic",
        "gemstone": "Citrine",
        "price": 1199,
        "originalPrice": 1599,
        "badge": "SALE",
        "swatches": ["#e67e22"],
        "concern": ["money", "peace"],
        "zodiac": ["Leo", "Sagittarius"],
        "chakra": "Solar Plexus Chakra",
        "description": "Brings the warmth of midsummer sunlight to your wrist, promoting joyful abundance and steady financial growth.",
    },
    "Lapis Lazuli": {
        "slug": "lapis-lazuli-classic",
        "name": "Royal Lapis Lazuli Sovereign Wisdom Bracelet",
        "beadSize": "8mm",
        "material": "Natural Afghan Lapis Lazuli with Gold Pyrite Specks",
        "gemstone": "Lapis Lazuli",
        "price": 1299,
        "originalPrice": 1799,
        "badge": "BEST SELLER",
        "swatches": ["#1d3557", "#c8a951"],
        "concern": ["peace", "protection"],
        "zodiac": ["Sagittarius", "Libra"],
        "chakra": "Throat & Third Eye Chakra",
        "description": "The sacred stone of ancient Pharaohs and celestial seers. Stimulates clear speech, honest communication, and profound insight.",
    },
    "Lapis Lazuli 10MM": {
        "slug": "lapis-lazuli-10mm",
        "name": "Celestial Lapis Lazuli 10MM Inner Truth Bracelet",
        "beadSize": "10mm",
        "material": "Deep Ultramarine Lapis (10mm), Pyrite Flecked",
        "gemstone": "Lapis Lazuli",
        "price": 1699,
        "originalPrice": 2299,
        "badge": "NEW",
        "swatches": ["#03045e", "#c8a951"],
        "concern": ["peace"],
        "zodiac": ["Sagittarius"],
        "chakra": "Throat & Third Eye",
        "description": "Rich royal blue 10mm beads with shimmering natural pyrite crystals provide an aura of undeniable dignity and poise.",
    },
    "Lapis Lazuli 8MM": {
        "slug": "lapis-lazuli-8mm",
        "name": "Celestial Lapis Lazuli 8MM Insight & Vision Bracelet",
        "beadSize": "8mm",
        "material": "Grade-A Lapis Lazuli (8mm), Stretch Cord",
        "gemstone": "Lapis Lazuli",
        "price": 1399,
        "originalPrice": 1899,
        "badge": None,
        "swatches": ["#1d3557"],
        "concern": ["peace", "protection"],
        "zodiac": ["Sagittarius", "Libra"],
        "chakra": "Throat Chakra",
        "description": "Connects intellectual discernment with spiritual understanding, liberating the voice from stage fright and anxiety.",
    },
    "Mahogany Obsidian": {
        "slug": "mahogany-obsidian-classic",
        "name": "Grounding Mahogany Obsidian Earth Shield Bracelet",
        "beadSize": "8mm",
        "material": "Natural Volcanic Mahogany Obsidian, Elastic",
        "gemstone": "Mahogany Obsidian",
        "price": 1099,
        "originalPrice": 1499,
        "badge": None,
        "swatches": ["#3d0c02", "#1a1a1a"],
        "concern": ["protection"],
        "zodiac": ["Scorpio", "Sagittarius"],
        "chakra": "Root & Sacral Chakra",
        "description": "Rich reddish-brown volcanic glass balances fierce protection with gentle, nurturing earth grounding.",
    },
    "Mahogany Obsidian 10mm": {
        "slug": "mahogany-obsidian-10mm",
        "name": "Mahogany Obsidian 10MM Strength & Release Bracelet",
        "beadSize": "10mm",
        "material": "Deep Brown-Black Obsidian (10mm), Elastic",
        "gemstone": "Mahogany Obsidian",
        "price": 1399,
        "originalPrice": 1799,
        "badge": "NEW",
        "swatches": ["#2b0900", "#111111"],
        "concern": ["protection"],
        "zodiac": ["Scorpio"],
        "chakra": "Root Chakra",
        "description": "10mm grounding beads pull excessive mental chatter down into the earth, relieving chronic emotional exhaustion.",
    },
    "Mahogany Obsidian 8MM": {
        "slug": "mahogany-obsidian-8mm",
        "name": "Mahogany Obsidian 8MM Gentle Protection Bracelet",
        "beadSize": "8mm",
        "material": "Polished Mahogany Obsidian (8mm), Elastic",
        "gemstone": "Mahogany Obsidian",
        "price": 1199,
        "originalPrice": 1599,
        "badge": "SALE",
        "swatches": ["#3d0c02"],
        "concern": ["protection"],
        "zodiac": ["Scorpio", "Sagittarius"],
        "chakra": "Root Chakra",
        "description": "Assists with severing karmic ties and attachments while protecting against psychic invasions.",
    },
    "Mix": {
        "slug": "multi-gemstone-harmony",
        "name": "Multi-Gemstone Cosmic Harmony Rainbow Bracelet",
        "beadSize": "8mm",
        "material": "Amethyst, Rose Quartz, Citrine, Aventurine, Lapis & Tiger Eye",
        "gemstone": "Multi-stone",
        "price": 1399,
        "originalPrice": 1899,
        "badge": "BEST SELLER",
        "swatches": ["#9c27b0", "#e91e63", "#ffeb3b", "#4caf50", "#2196f3"],
        "concern": ["peace", "love", "money", "protection", "health"],
        "zodiac": ["All Signs"],
        "chakra": "All 7 Chakras",
        "description": "A complete spectrum of crystalline harmony. Aligns the bio-energetic meridians from root to crown in complete balance.",
    },
    "Natural Citrine": {
        "slug": "natural-citrine-classic",
        "name": "Rare Untreated Natural Kundalini Citrine Bracelet",
        "beadSize": "8mm",
        "material": "100% Earth-Mined Natural Citrine, Elastic",
        "gemstone": "Natural Citrine",
        "price": 1699,
        "originalPrice": 2299,
        "badge": "BEST SELLER",
        "swatches": ["#d4af37", "#f4d03f"],
        "concern": ["money"],
        "zodiac": ["Leo", "Gemini"],
        "chakra": "Solar Plexus Chakra",
        "description": "Pure untreated Kundalini Citrine from the Congo. Smoky golden hues signify authentic geological genesis, free of thermal treatment.",
    },
    "Natural Citrine 10MM": {
        "slug": "natural-citrine-10mm",
        "name": "Natural Kundalini Citrine 10MM Pure Wealth Magnet Bracelet",
        "beadSize": "10mm",
        "material": "Untreated Geological Citrine (10mm), Elastic",
        "gemstone": "Natural Citrine",
        "price": 2199,
        "originalPrice": 2899,
        "badge": "NEW",
        "swatches": ["#c59b27", "#e5c07b"],
        "concern": ["money"],
        "zodiac": ["Leo", "Gemini"],
        "chakra": "Solar Plexus Chakra",
        "description": "Rare collector's grade 10mm spheres of genuine untreated Citrine. The definitive physical anchor for monumental abundance.",
    },
    "Natural Citrine 8MM": {
        "slug": "natural-citrine-8mm",
        "name": "Natural Kundalini Citrine 8MM Manifestation Bracelet",
        "beadSize": "8mm",
        "material": "Natural Earth-Grown Citrine (8mm), Elastic",
        "gemstone": "Natural Citrine",
        "price": 1799,
        "originalPrice": 2399,
        "badge": "SALE",
        "swatches": ["#d4af37"],
        "concern": ["money"],
        "zodiac": ["Leo", "Gemini"],
        "chakra": "Solar Plexus Chakra",
        "description": "Holds the pure vibration of golden sunlight trapped in crystalline quartz over millions of years.",
    },
    "Pyrite": {
        "slug": "pyrite-classic",
        "name": "Golden Pyrite Iron Sun Wealth Armor Bracelet",
        "beadSize": "8mm",
        "material": "Peruvian Natural Pyrite Spheres, Elastic",
        "gemstone": "Pyrite",
        "price": 1199,
        "originalPrice": 1599,
        "badge": "BEST SELLER",
        "swatches": ["#c8a951", "#b8973d"],
        "concern": ["money", "protection"],
        "zodiac": ["Leo", "Capricorn"],
        "chakra": "Solar Plexus Chakra",
        "description": "Known as Fool's Gold, this metallic mineral possesses fierce masculine sun energy. Blocks financial leaks and attracts sudden wealth.",
    },
    "Pyrite 10MM": {
        "slug": "pyrite-10mm",
        "name": "Golden Pyrite 10MM Abundance & Wealth Magnet Bracelet",
        "beadSize": "10mm",
        "material": "Dense Metallic Pyrite (10mm), Heavy Duty Cord",
        "gemstone": "Pyrite",
        "price": 1599,
        "originalPrice": 2099,
        "badge": "NEW",
        "swatches": ["#a5762a", "#c8a951"],
        "concern": ["money", "protection"],
        "zodiac": ["Leo", "Capricorn"],
        "chakra": "Solar Plexus Chakra",
        "description": "Heavy, weighty 10mm Pyrite beads instill an unshakeable aura of authority, financial abundance, and leadership prowess.",
    },
    "Pyrite 8MM": {
        "slug": "pyrite-8mm",
        "name": "Golden Pyrite 8MM Prosperity & Solar Power Bracelet",
        "beadSize": "8mm",
        "material": "High-Grade Peruvian Pyrite (8mm), Elastic",
        "gemstone": "Pyrite",
        "price": 1299,
        "originalPrice": 1699,
        "badge": "SALE",
        "swatches": ["#c8a951"],
        "concern": ["money"],
        "zodiac": ["Leo"],
        "chakra": "Solar Plexus Chakra",
        "description": "Essential gemstone remedy for entrepreneurs and professionals seeking to break through financial ceilings.",
    },
    "Red Jasper": {
        "slug": "red-jasper-classic",
        "name": "Sacred Red Jasper Supreme Nurturer Bracelet",
        "beadSize": "8mm",
        "material": "Deep Terracotta Red Jasper, Elastic Cord",
        "gemstone": "Red Jasper",
        "price": 999,
        "originalPrice": 1399,
        "badge": "BEST SELLER",
        "swatches": ["#a03020", "#c0392b"],
        "concern": ["health"],
        "zodiac": ["Aries", "Scorpio"],
        "chakra": "Root Chakra",
        "description": "Ancient warrior talisman. Grounding and stabilizing, providing quiet strength in emotional crisis and sustaining physical stamina.",
    },
    "Red Jasper 10MM": {
        "slug": "red-jasper-10mm",
        "name": "Red Jasper 10MM Earth Grounding & Stamina Bracelet",
        "beadSize": "10mm",
        "material": "Dense Red Jasper Beads (10mm), Elastic",
        "gemstone": "Red Jasper",
        "price": 1299,
        "originalPrice": 1699,
        "badge": "NEW",
        "swatches": ["#872314", "#a03020"],
        "concern": ["health"],
        "zodiac": ["Aries", "Scorpio"],
        "chakra": "Root Chakra",
        "description": "10mm earthy beads reconnect the subtle body directly to Mother Earth, dispersing inertia and self-defeating patterns.",
    },
    "Red Jasper 8MM": {
        "slug": "red-jasper-8mm",
        "name": "Red Jasper 8MM Physical Endurance & Courage Bracelet",
        "beadSize": "8mm",
        "material": "Selected Red Jasper (8mm), Elastic",
        "gemstone": "Red Jasper",
        "price": 1099,
        "originalPrice": 1499,
        "badge": None,
        "swatches": ["#a03020"],
        "concern": ["health"],
        "zodiac": ["Aries"],
        "chakra": "Root Chakra",
        "description": "Awakens Kundalini serpent energy safely at the base of the spine, fueling healthy ambition and stamina.",
    },
    "Rhodochrosite 8MM": {
        "slug": "rhodochrosite-8mm",
        "name": "Sacred Inca Rose Rhodochrosite 8MM Divine Love Bracelet",
        "beadSize": "8mm",
        "material": "Natural Pink Argentinian Rhodochrosite (8mm), Elastic",
        "gemstone": "Rhodochrosite",
        "price": 1899,
        "originalPrice": 2499,
        "badge": "BEST SELLER",
        "swatches": ["#e056fd", "#ff7979", "#f6e58d"],
        "concern": ["love", "peace"],
        "zodiac": ["Leo", "Scorpio"],
        "chakra": "Heart & Solar Plexus",
        "description": "The national gemstone of Argentina with raspberry pink banding. Heals deep inner-child wounds, dissolves grief, and magnetizes soulmate connections.",
    },
    "Rhodonite 10MM": {
        "slug": "rhodonite-10mm",
        "name": "Rhodonite 10MM Emotional Rescue & Forgiveness Bracelet",
        "beadSize": "10mm",
        "material": "Rose-Pink & Black Dendritic Rhodonite (10mm), Elastic",
        "gemstone": "Rhodonite",
        "price": 1499,
        "originalPrice": 1999,
        "badge": "NEW",
        "swatches": ["#c2185b", "#212121"],
        "concern": ["love", "peace"],
        "zodiac": ["Taurus"],
        "chakra": "Heart Chakra",
        "description": "Features captivating black manganese inclusions that ground emotional shock, panic, and heartbreaks.",
    },
    "Rhodonite 8MM": {
        "slug": "rhodonite-8mm",
        "name": "Rhodonite 8MM Heart Clearing & Compassion Bracelet",
        "beadSize": "8mm",
        "material": "Natural Pink Rhodonite (8mm), Stretch String",
        "gemstone": "Rhodonite",
        "price": 1299,
        "originalPrice": 1699,
        "badge": "SALE",
        "swatches": ["#c2185b", "#f48fb1"],
        "concern": ["love"],
        "zodiac": ["Taurus"],
        "chakra": "Heart Chakra",
        "description": "Fosters self-worth, emotional maturity, and the grace to forgive past relationship betrayals.",
    },
    "Rose Quartz": {
        "slug": "rose-quartz-classic",
        "name": "Madagascar Rose Quartz Unconditional Love Bracelet",
        "beadSize": "8mm",
        "material": "Soft Pink Madagascar Rose Quartz, Elastic",
        "gemstone": "Rose Quartz",
        "price": 1099,
        "originalPrice": 1499,
        "badge": "BEST SELLER",
        "swatches": ["#f48fb1", "#f8bbd9"],
        "concern": ["love", "peace"],
        "zodiac": ["Taurus", "Libra"],
        "chakra": "Heart Chakra",
        "description": "The quintessential stone of unconditional love. Opens the heart to receive romance, friendship, and profound self-worth.",
    },
    "Rose Quartz 10MM": {
        "slug": "rose-quartz-10mm",
        "name": "Madagascar Rose Quartz 10MM Emotional Healing Bracelet",
        "beadSize": "10mm",
        "material": "Translucent Pink Rose Quartz (10mm), Strong Elastic",
        "gemstone": "Rose Quartz",
        "price": 1399,
        "originalPrice": 1799,
        "badge": "NEW",
        "swatches": ["#f48fb1"],
        "concern": ["love"],
        "zodiac": ["Taurus", "Libra"],
        "chakra": "Heart Chakra",
        "description": "Luminous 10mm pink spheres transmit soothing frequencies that melt emotional ice and invite tender affection.",
    },
    "Rose Quartz 8MM": {
        "slug": "rose-quartz-8mm",
        "name": "Madagascar Rose Quartz 8MM Loving Grace Bracelet",
        "beadSize": "8mm",
        "material": "Grade-A Rose Quartz Spheres (8mm), Elastic",
        "gemstone": "Rose Quartz",
        "price": 1199,
        "originalPrice": 1599,
        "badge": "SALE",
        "swatches": ["#f48fb1", "#fce4ec"],
        "concern": ["love"],
        "zodiac": ["Taurus", "Libra"],
        "chakra": "Heart Chakra",
        "description": "A must-have foundational crystal. Radiates gentleness and tenderness across all interpersonal relationships.",
    },
    "Selenite": {
        "slug": "selenite-classic",
        "name": "Divine Light Selenite Lunar Cleansing Bracelet",
        "beadSize": "8mm",
        "material": "Silky White Moroccan Selenite (Gypsum), Elastic",
        "gemstone": "Selenite",
        "price": 999,
        "originalPrice": 1399,
        "badge": "BEST SELLER",
        "swatches": ["#ffffff", "#f5f5f5"],
        "concern": ["peace", "protection"],
        "zodiac": ["Cancer", "Taurus"],
        "chakra": "Crown & Third Eye",
        "description": "Named after Selene, the Greek Moon Goddess. Holds liquid white light frequency, automatically purifying the other crystals on your wrist.",
    },
    "Selenite 10MM": {
        "slug": "selenite-10mm",
        "name": "White Satin Selenite 10MM Angelic Ray Bracelet",
        "beadSize": "10mm",
        "material": "Satin Spar Selenite (10mm), Elastic Cord",
        "gemstone": "Selenite",
        "price": 1299,
        "originalPrice": 1699,
        "badge": "NEW",
        "swatches": ["#ffffff"],
        "concern": ["peace"],
        "zodiac": ["Cancer"],
        "chakra": "Crown Chakra",
        "description": "10mm luminous spheres of fiber-optic Selenite connect your consciousness with angelic guidance and higher wisdom.",
    },
    "Selenite 8MM": {
        "slug": "selenite-8mm",
        "name": "White Satin Selenite 8MM Moonbeam Purifying Bracelet",
        "beadSize": "8mm",
        "material": "Selected Selenite Gypsum (8mm), Elastic",
        "gemstone": "Selenite",
        "price": 1099,
        "originalPrice": 1499,
        "badge": "SALE",
        "swatches": ["#ffffff", "#fafafa"],
        "concern": ["peace", "protection"],
        "zodiac": ["Cancer"],
        "chakra": "Crown Chakra",
        "description": "Provides instant relief from energetic heaviness after crowded social events or taxing meetings.",
    },
    "Suleman Hakik 8MM": {
        "slug": "sulemani-hakik-8mm",
        "name": "Mystical Sulemani Hakik 8MM Nazar Suraksha Bracelet",
        "beadSize": "8mm",
        "material": "Natural Sulemani Agate (8mm), Durable Cord",
        "gemstone": "Sulemani Hakik",
        "price": 1199,
        "originalPrice": 1599,
        "badge": "BEST SELLER",
        "swatches": ["#212121", "#757575"],
        "concern": ["protection"],
        "zodiac": ["Capricorn", "Aquarius"],
        "chakra": "Root Chakra",
        "description": "Ancient Vedic protection amulet against Evil Eye (Buri Nazar), psychic envy, and dark planetary afflictions.",
    },
    "Sulemani Hakik": {
        "slug": "sulemani-hakik-classic",
        "name": "Classic Sulemani Hakik Evil Eye Ward Bracelet",
        "beadSize": "8mm",
        "material": "Black & Grey Banded Agate, Elastic",
        "gemstone": "Sulemani Hakik",
        "price": 1099,
        "originalPrice": 1499,
        "badge": "SALE",
        "swatches": ["#1a1a1a", "#9e9e9e"],
        "concern": ["protection"],
        "zodiac": ["Capricorn"],
        "chakra": "Root Chakra",
        "description": "Neutralizes planetary malefic effects of Rahu and Ketu, creating a stable mental anchor during challenging transits.",
    },
    "Sulemani Hakik 10MM": {
        "slug": "sulemani-hakik-10mm",
        "name": "Sulemani Hakik 10MM Rahu-Ketu Pacifying Bracelet",
        "beadSize": "10mm",
        "material": "Heavy Banded Sulemani Agate (10mm), Elastic",
        "gemstone": "Sulemani Hakik",
        "price": 1499,
        "originalPrice": 1999,
        "badge": "NEW",
        "swatches": ["#000000", "#616161"],
        "concern": ["protection"],
        "zodiac": ["Capricorn", "Aquarius"],
        "chakra": "Root Chakra",
        "description": "Robust 10mm agate beads with natural geological banding, absorbing heavy negative energies from your surroundings.",
    },
    "Sulemani Hakik Red 10MM": {
        "slug": "sulemani-hakik-red-10mm",
        "name": "Rare Red Sulemani Hakik 10MM Courage & Shield Bracelet",
        "beadSize": "10mm",
        "material": "Natural Red Banded Agate (10mm), Elastic",
        "gemstone": "Sulemani Hakik",
        "price": 1599,
        "originalPrice": 2199,
        "badge": "NEW",
        "swatches": ["#8b0000", "#d32f2f"],
        "concern": ["protection", "health"],
        "zodiac": ["Aries", "Scorpio"],
        "chakra": "Root & Sacral Chakra",
        "description": "Rare red-hued Sulemani Agate spheres combine warrior courage with impenetrable occult shielding.",
    },
    "Sunstone": {
        "slug": "sunstone-classic",
        "name": "Sparkling Sunstone Solar Leadership Bracelet",
        "beadSize": "8mm",
        "material": "Natural Oregon-Style Aventurine Sunstone, Elastic",
        "gemstone": "Sunstone",
        "price": 1299,
        "originalPrice": 1699,
        "badge": "BEST SELLER",
        "swatches": ["#e67e22", "#f39c12"],
        "concern": ["money", "love"],
        "zodiac": ["Leo", "Libra"],
        "chakra": "Sacral & Solar Plexus",
        "description": "Infused with golden hematite or copper platelets that shimmer under sunlight, awakening leadership magnetism and boundless vitality.",
    },
    "Sunstone 10MM": {
        "slug": "sunstone-10mm",
        "name": "Golden Sunstone 10MM Sovereign Charisma Bracelet",
        "beadSize": "10mm",
        "material": "Shimmering Sunstone Spheres (10mm), Elastic",
        "gemstone": "Sunstone",
        "price": 1599,
        "originalPrice": 2099,
        "badge": "NEW",
        "swatches": ["#d35400", "#f39c12"],
        "concern": ["money"],
        "zodiac": ["Leo"],
        "chakra": "Solar Plexus Chakra",
        "description": "10mm golden solar beads boost masculine Yang energy, career authority, and authentic stage presence.",
    },
    "Sunstone 8MM": {
        "slug": "sunstone-8mm",
        "name": "Golden Sunstone 8MM Joy & Pranic Radiance Bracelet",
        "beadSize": "8mm",
        "material": "Polished Natural Sunstone (8mm), Elastic",
        "gemstone": "Sunstone",
        "price": 1399,
        "originalPrice": 1799,
        "badge": "SALE",
        "swatches": ["#e67e22"],
        "concern": ["money", "love"],
        "zodiac": ["Leo", "Libra"],
        "chakra": "Sacral & Solar Plexus",
        "description": "Dispels seasonal affective melancholy and codependency, encouraging you to shine your authentic light unapologetically.",
    },
    "Tiger Eye": {
        "slug": "tiger-eye-classic",
        "name": "Golden Tiger Eye Fearless Action Bracelet",
        "beadSize": "8mm",
        "material": "Chatoyant Golden-Brown Tiger Eye, Elastic",
        "gemstone": "Tiger Eye",
        "price": 1099,
        "originalPrice": 1499,
        "badge": "BEST SELLER",
        "swatches": ["#8b6914", "#c8a951"],
        "concern": ["money", "protection"],
        "zodiac": ["Gemini", "Leo", "Capricorn"],
        "chakra": "Solar Plexus & Root",
        "description": "Classic stone of courage, discernment, and practical focus. Helps navigate complex business negotiations with predatory precision.",
    },
    "Tiger Eye 10MM": {
        "slug": "tiger-eye-10mm",
        "name": "Golden Tiger Eye 10MM Courage & Grounding Bracelet",
        "beadSize": "10mm",
        "material": "Rich Banded Tiger Eye (10mm), Strong Elastic",
        "gemstone": "Tiger Eye",
        "price": 1399,
        "originalPrice": 1799,
        "badge": "NEW",
        "swatches": ["#6b4e07", "#8b6914"],
        "concern": ["money", "protection"],
        "zodiac": ["Leo", "Capricorn"],
        "chakra": "Solar Plexus Chakra",
        "description": "Substantial 10mm chatoyant spheres shimmer like molten gold under light, repelling self-doubt and fear of failure.",
    },
    "Tiger Eye 8MM": {
        "slug": "tiger-eye-8mm",
        "name": "Golden Tiger Eye 8MM Clarity & Confidence Bracelet",
        "beadSize": "8mm",
        "material": "Grade-A Tiger Eye (8mm), Elastic Cord",
        "gemstone": "Tiger Eye",
        "price": 1199,
        "originalPrice": 1599,
        "badge": "SALE",
        "swatches": ["#8b6914"],
        "concern": ["money", "protection"],
        "zodiac": ["Gemini", "Leo"],
        "chakra": "Solar Plexus Chakra",
        "description": "Balances solar and terrestrial energies, keeping you grounded while pursuing ambitious financial horizons.",
    },
    "Turquoise": {
        "slug": "turquoise-classic",
        "name": "Tibetan Turquoise Sacred Sky Healer Bracelet",
        "beadSize": "8mm",
        "material": "Natural Turquoise with Matrix, Elastic",
        "gemstone": "Turquoise",
        "price": 1399,
        "originalPrice": 1899,
        "badge": "BEST SELLER",
        "swatches": ["#16a085", "#1abc9c"],
        "concern": ["health", "protection"],
        "zodiac": ["Sagittarius", "Pisces"],
        "chakra": "Throat Chakra",
        "description": "Cherished for thousands of years by Himalayan shamans. A premier master healing stone that protects travelers and aligns all meridians.",
    },
    "Turquoise 10MM": {
        "slug": "turquoise-10mm",
        "name": "Natural Turquoise 10MM Traveler Protection Bracelet",
        "beadSize": "10mm",
        "material": "Selected Turquoise (10mm), Heavy Duty Elastic",
        "gemstone": "Turquoise",
        "price": 1799,
        "originalPrice": 2399,
        "badge": "NEW",
        "swatches": ["#0e6655", "#16a085"],
        "concern": ["protection", "health"],
        "zodiac": ["Sagittarius"],
        "chakra": "Throat Chakra",
        "description": "Bold 10mm robin-egg turquoise beads provide profound energetic cushioning during long journeys and major life transitions.",
    },
    "Turquoise 8MM": {
        "slug": "turquoise-8mm",
        "name": "Natural Turquoise 8MM Serenity & Communication Bracelet",
        "beadSize": "8mm",
        "material": "Natural Turquoise Beads (8mm), Elastic",
        "gemstone": "Turquoise",
        "price": 1499,
        "originalPrice": 1999,
        "badge": "SALE",
        "swatches": ["#16a085"],
        "concern": ["peace", "health"],
        "zodiac": ["Sagittarius", "Pisces"],
        "chakra": "Throat Chakra",
        "description": "Promotes peaceful communication, dissolves creative blocks, and shields against psychic depletion.",
    },
    "Turquoise Gem 10MM": {
        "slug": "turquoise-gem-10mm",
        "name": "Gem-Grade Turquoise 10MM Master Blessing Bracelet",
        "beadSize": "10mm Gem",
        "material": "Premium Sleeping Beauty Quality Turquoise (10mm)",
        "gemstone": "Turquoise",
        "price": 2199,
        "originalPrice": 2899,
        "badge": "NEW",
        "swatches": ["#00bcd4", "#0097a7"],
        "concern": ["health", "protection"],
        "zodiac": ["Sagittarius"],
        "chakra": "Throat Chakra",
        "description": "Flawless cyan-blue gem-grade turquoise spheres of museum quality, sanctified for spiritual leadership and total health rejuvenation.",
    },
    "Turquoise Gem 8MM": {
        "slug": "turquoise-gem-8mm",
        "name": "Gem-Grade Turquoise 8MM Celestial Blue Bracelet",
        "beadSize": "8mm Gem",
        "material": "Gem-Grade Natural Turquoise (8mm), Elastic",
        "gemstone": "Turquoise",
        "price": 1899,
        "originalPrice": 2499,
        "badge": "BEST SELLER",
        "swatches": ["#00bcd4"],
        "concern": ["health", "peace"],
        "zodiac": ["Sagittarius", "Pisces"],
        "chakra": "Throat Chakra",
        "description": "Pristine vibrant blue beads devoid of harsh matrix, delivering pure throat-chakra resonance.",
    },
    "Unakite": {
        "slug": "unakite-classic",
        "name": "Unakite Epidote Vision & Rebirth Bracelet",
        "beadSize": "8mm",
        "material": "Natural Green Epidote & Pink Feldspar Unakite",
        "gemstone": "Unakite",
        "price": 999,
        "originalPrice": 1399,
        "badge": "BEST SELLER",
        "swatches": ["#556b2f", "#f48fb1"],
        "concern": ["health", "love"],
        "zodiac": ["Scorpio", "Taurus"],
        "chakra": "Heart & Third Eye",
        "description": "Harmonious union of forest green Epidote and delicate salmon-pink Feldspar. Nurtures emotional balance during rebirth and pregnancy.",
    },
    "Unakite 10MM": {
        "slug": "unakite-10mm",
        "name": "Unakite Jasper 10MM Emotional Healing & Rebirth Bracelet",
        "beadSize": "10mm",
        "material": "Selected Unakite (10mm), Heavy Duty Elastic",
        "gemstone": "Unakite",
        "price": 1299,
        "originalPrice": 1699,
        "badge": "NEW",
        "swatches": ["#425424", "#e27b9c"],
        "concern": ["health"],
        "zodiac": ["Scorpio"],
        "chakra": "Heart Chakra",
        "description": "10mm earthy beads release buried emotional trauma from the heart and cellular memory, assisting in deep convalescence.",
    },
    "Unakite 8MM": {
        "slug": "unakite-8mm",
        "name": "Unakite Jasper 8MM Fertility & Balance Bracelet",
        "beadSize": "8mm",
        "material": "Grade-A Unakite (8mm), Elastic Cord",
        "gemstone": "Unakite",
        "price": 1099,
        "originalPrice": 1499,
        "badge": "SALE",
        "swatches": ["#556b2f", "#f48fb1"],
        "concern": ["health", "love"],
        "zodiac": ["Scorpio", "Taurus"],
        "chakra": "Heart Chakra",
        "description": "Renowned talisman for healthy reproductive balance, harmonious partnerships, and grounded emotional healing.",
    },
    "Ying Yang": {
        "slug": "yin-yang-harmony",
        "name": "Yin Yang Dual Harmony Balancing Bracelet",
        "beadSize": "8mm",
        "material": "Black Obsidian & White Howlite Dual Polarity Beads",
        "gemstone": "Multi-stone",
        "price": 1299,
        "originalPrice": 1699,
        "badge": "BEST SELLER",
        "swatches": ["#111111", "#f5f5f5"],
        "concern": ["protection", "peace"],
        "zodiac": ["Gemini", "Libra", "Pisces"],
        "chakra": "Root & Crown Chakra",
        "description": "Embodying the ancient Taoist principle of polar equilibrium. Integrates shadow and light, masculine and feminine, logic and intuition.",
    },
}

def process_single_image(args):
    in_path, out_path = args
    try:
        if os.path.exists(out_path) and os.path.getsize(out_path) > 1000:
            return out_path
        im = Image.open(in_path)
        im.thumbnail((1200, 1200), Image.Resampling.LANCZOS)
        im.save(out_path, "WEBP", quality=85)
        return out_path
    except Exception as e:
        print(f"Error processing {in_path}: {e}")
        return None

def main():
    print(f"Starting catalogue processing for {len(PRODUCT_CONFIGS)} products...")
    t0 = time.time()
    
    tasks = []
    product_images_map = {}
    
    for folder, config in PRODUCT_CONFIGS.items():
        folder_path = os.path.join(BASE_DIR, folder)
        if not os.path.exists(folder_path):
            print(f"WARNING: Folder {folder_path} not found!")
            continue
            
        slug = config["slug"]
        product_out_dir = os.path.join(OUT_BASE, slug)
        os.makedirs(product_out_dir, exist_ok=True)
        
        # Sort image files naturally
        files = sorted(
            [f for f in os.listdir(folder_path) if not f.startswith('.')],
            key=lambda x: [int(c) if c.isdigit() else c.lower() for c in re.split(r'(\d+)', x)]
        )
        
        web_paths = []
        for idx, f in enumerate(files):
            in_file = os.path.join(folder_path, f)
            out_file_name = f"image-{idx+1}.webp"
            out_file_path = os.path.join(product_out_dir, out_file_name)
            tasks.append((in_file, out_file_path))
            web_paths.append(f"/products/{slug}/{out_file_name}")
            
        product_images_map[folder] = web_paths
        
    print(f"Total images to process across all products: {len(tasks)}")
    
    # Process images with ThreadPoolExecutor
    with ThreadPoolExecutor(max_workers=8) as executor:
        results = list(executor.map(process_single_image, tasks))
        
    success_count = len([r for r in results if r is not None])
    print(f"Successfully processed {success_count}/{len(tasks)} images in {time.time()-t0:.2f} seconds!")
    
    # Now generate the products list
    products_list = []
    pid = 1
    
    for folder, config in PRODUCT_CONFIGS.items():
        images = product_images_map.get(folder, [])
        if not images:
            continue
            
        primary_image = images[0]
        
        orig_price = config.get("originalPrice", int(config["price"] * 1.3))
        save_pct = int(round((orig_price - config["price"]) / orig_price * 100))
        
        prod = {
            "id": pid,
            "name": config["name"],
            "price": config["price"],
            "originalPrice": orig_price,
            "material": config["material"],
            "category": "bracelets",
            "gemstone": config["gemstone"],
            "image": primary_image,
            "images": images,
            "badge": config.get("badge"),
            "savePercent": save_pct,
            "swatches": config.get("swatches", ["#c8a951"]),
            "concern": config.get("concern", ["peace"]),
            "isNew": config.get("badge") == "NEW",
            "isBestSeller": config.get("badge") == "BEST SELLER",
            "beadSize": config.get("beadSize", "8mm"),
            "zodiac": config.get("zodiac", []),
            "chakra": config.get("chakra", ""),
            "description": config.get("description", ""),
        }
        products_list.append(prod)
        pid += 1
        
    print(f"Generated {len(products_list)} product definitions.")
    
    # Save JSON intermediate for validation
    with open("scripts/generated_products.json", "w", encoding="utf-8") as f:
        json.dump(products_list, f, indent=2)
        
    # Generate TypeScript file
    generate_ts_file(products_list)
    print("products.ts successfully generated!")

def generate_ts_file(products_list):
    ts_content = '''export interface Product {
  id: number;
  name: string;
  price: number;
  originalPrice?: number;
  material: string;
  category: string;
  gemstone?: string;
  image: string;
  images?: string[];
  badge?: "NEW" | "SALE" | "SOLD OUT" | "BEST SELLER";
  savePercent?: number;
  swatches?: string[];
  concern?: string[];
  isNew?: boolean;
  isBestSeller?: boolean;
  beadSize?: string;
  zodiac?: string[];
  chakra?: string;
  description?: string;
}

export const categories = [
  { id: "bracelets",  name: "All Bracelets",             image: "/cat-bracelets.webp",  count: ''' + str(len(products_list)) + ''' },
  { id: "pendants",   name: "Pendants",                  image: "/cat-pendants.webp",   count: 51 },
  { id: "rings",      name: "Rings",                     image: "/cat-rings.webp",       count: 28 },
  { id: "necklaces",  name: "Necklaces & Mala",          image: "/cat-necklaces.webp",  count: 22 },
  { id: "ear-studs",  name: "Ear Studs & Anklets",       image: "/cat-ear-studs.webp",  count: 18 },
  { id: "gemstones",  name: "Gemstones & Raw Crystals",  image: "/cat-gemstones.webp",  count: 34 },
];

export const concerns = [
  { id: "love",       name: "Love",       subtitle: "OPEN YOUR HEART",    image: "/concern-love.webp",       description: "Rose Quartz, Rhodochrosite, Rhodonite" },
  { id: "peace",      name: "Peace",      subtitle: "RELIEVE YOUR STRESS", image: "/concern-peace.webp",      description: "Amethyst, Amazonite, Selenite" },
  { id: "protection", name: "Protection", subtitle: "SHIELD YOUR ENERGY",  image: "/concern-protection.webp", description: "Black Tourmaline, Sulemani Hakik, Obsidian" },
  { id: "money",      name: "Money",      subtitle: "ATTRACT ABUNDANCE",   image: "/concern-money.webp",      description: "Citrine, Pyrite, Green Aventurine, Dhan Yog" },
  { id: "health",     name: "Health",     subtitle: "HEAL YOUR BODY",      image: "/concern-health.webp",     description: "Clear Quartz, Carnelian, Red Jasper, Turquoise" },
];

export const zodiacSigns = [
  { sign: "Aries",       dates: "Mar 21 – Apr 19", crystal: "Carnelian",     emoji: "♈" },
  { sign: "Taurus",      dates: "Apr 20 – May 20", crystal: "Rose Quartz",   emoji: "♉" },
  { sign: "Gemini",      dates: "May 21 – Jun 20", crystal: "Tiger Eye",     emoji: "♊" },
  { sign: "Cancer",      dates: "Jun 21 – Jul 22", crystal: "Selenite",      emoji: "♋" },
  { sign: "Leo",         dates: "Jul 23 – Aug 22", crystal: "Citrine",       emoji: "♌" },
  { sign: "Virgo",       dates: "Aug 23 – Sep 22", crystal: "Amazonite",     emoji: "♍" },
  { sign: "Libra",       dates: "Sep 23 – Oct 22", crystal: "Lapis Lazuli",  emoji: "♎" },
  { sign: "Scorpio",     dates: "Oct 23 – Nov 21", crystal: "Unakite",       emoji: "♏" },
  { sign: "Sagittarius", dates: "Nov 22 – Dec 21", crystal: "Turquoise",     emoji: "♐" },
  { sign: "Capricorn",   dates: "Dec 22 – Jan 19", crystal: "Garnet",        emoji: "♑" },
  { sign: "Aquarius",    dates: "Jan 20 – Feb 18", crystal: "Amethyst",      emoji: "♒" },
  { sign: "Pisces",      dates: "Feb 19 – Mar 20", crystal: "Clear Quartz",  emoji: "♓" },
];

export const products: Product[] = ''' + json.dumps(products_list, indent=2) + ''';

export const newArrivals = products.filter(p => p.isNew);
export const bestSellers = products.filter(p => p.isBestSeller);
'''
    with open("src/data/products.ts", "w", encoding="utf-8") as f:
        f.write(ts_content)

if __name__ == "__main__":
    main()
